In [17]:
import pandas
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

In [18]:
uri = "mongodb+srv://Sujatmiko:Sujatmiko123@learning-buddy.jlyprnn.mongodb.net/?appName=Learning-Buddy"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [19]:
df_1= pandas.read_excel('ResourceData.xlsx', sheet_name='Learning Path Answer')
df_2= pandas.read_excel('ResourceData.xlsx', sheet_name='Current Interest Questions')
df_3= pandas.read_excel('ResourceData.xlsx', sheet_name='Current Tech Questions')
df_4= pandas.read_excel('ResourceData.xlsx', sheet_name='Skill Keywords')
df_5= pandas.read_excel('ResourceData.xlsx', sheet_name='Student Progress')

In [21]:
display (df_1.head())
display (df_2.head())
display (df_3.head())
display (df_4.head())
display (df_5.head())

,id,name,summary,description,course_difficulty,course_price,technologies,course_type,courseMeta,courseInfo
0,14,Belajar Fundamental Aplikasi Android,Pelajari skill Android dengan kurikulum terlen...,Android merupakan sistem operasi mobile dengan...,Menengah,PAID,Android,Picodiploma,"['140 Jam', '4,84', 'Menengah']","['107 Modul', '41.831 Siswa Terdaftar']"
1,32,Belajar Membangun LINE Chatbot,Belajar membuat chatbot yang menarik pada plat...,LINE merupakan platform komunikasi yang sangat...,Pemula,PAID,"Android,Chatbot,Web",Reguler,"['20 Jam', '4,89', 'Pemula']","['26 Modul', '15.478 Siswa Terdaftar']"
2,51,Belajar Membuat Aplikasi Android untuk Pemula,Buat aplikasi pertamamu pada Android Studio de...,Android merupakan sistem operasi mobile dengan...,Pemula,PAID,Android,Reguler,"['60 Jam', '4,87', 'Pemula']","['49 Modul', '116.344 Siswa Terdaftar']"
3,60,Memulai Pemrograman Dengan Java,Belajar bahasa Java buat kamu yang ingin mempe...,Java merupakan bahasa yang diciptakan oleh Jam...,Dasar,FREE,"Android,Multi Platform",Reguler,"['15 Jam', '4,86', 'Dasar']","['42 Modul', '80.316 Siswa Terdaftar']"
4,80,Memulai Pemrograman dengan Kotlin,"Pelajari dasar bahasa pemrograman, functional ...",Kotlin merupakan bahasa utama yang digunakan d...,"Dasar,Pemula",PAID,"Android,Multi Platform",Reguler,"['50 Jam', '4,84', 'Dasar - Pemula']","['132 Modul', '59.512 Siswa Terdaftar']"

,question_desc,option_text,category
0,Mana kegiatan yang paling relate denganmu di p...,Mencoba membuat menu sarapan,Mobile Development
1,Mana kegiatan yang paling relate denganmu di p...,Baca atau lihat info viral dari berbagai sumber,Artificial Intelligence
2,Mana kegiatan yang paling relate denganmu di p...,Membersihkan kamar,Cloud Computing
3,Mana kegiatan yang paling relate denganmu di p...,Coret-coret atau menulis di buku,Web Development
4,"Jika sedang menghadapi masalah, cara mana yang...",Coba berbagai cara sampai menemukan solusinya,Mobile Development

,tech_category,difficulty,question_desc,option_1,option_2,option_3,option_4,correct_answer
0,Android,beginner,Apa yang dimaksud dengan Activity dalam pengem...,Komponen yang menangani tampilan pengguna,Kelas untuk menyimpan data,Fungsi untuk menjalankan proses di latar belakang,Antarmuka untuk menghubungkan database,Komponen yang menangani tampilan pengguna
1,Android,beginner,Apa fungsi utama dari file AndroidManifest.xml?,Menyimpan data aplikasi,Mendefinisikan struktur dan metadata aplikasi,Mengatur tata letak UI,Mengelola dependensi proyek,Mendefinisikan struktur dan metadata aplikasi
2,Android,beginner,"Dalam konteks Android, apa yang dimaksud denga...",Komponen untuk menyimpan data,Mekanisme untuk navigasi antar Activity,Fungsi untuk menangani error,Framework untuk membuat UI,Mekanisme untuk navigasi antar Activity
3,Android,beginner,Apa perbedaan utama antara LinearLayout dan Re...,"LinearLayout hanya untuk orientasi vertikal, R...","LinearLayout mengatur elemen secara berurutan,...","LinearLayout untuk aplikasi sederhana, Relativ...","Tidak ada perbedaan, keduanya dapat digunakan ...","LinearLayout mengatur elemen secara berurutan,..."
4,Android,beginner,Apa fungsi dari metode onCreate() dalam sebuah...,Menghapus Activity,Menginisialisasi Activity dan memuat layout,Menjalankan proses di background,Mengatur animasi transisi,Menginisialisasi Activity dan memuat layout

   id     keyword
0   4  JavaScript
1   9        Java
2  14      Python
3  19      Kotlin
4  24         PHP

,name,email,course_name,active_tutorials,completed_tutorials,is_graduated,already_generated_certificate,final_submission_id,submission_rating,final_exam_id,exam_score
0,Dina Wijaya,dina.wijaya1@example.com,Belajar Membangun Aplikasi Android Native Bagi...,4,0,0,0,4.0,NaN,NaN,NaN
1,Irfan Halim,irfan.halim2@example.com,Belajar Membangun Aplikasi dengan Universal Wi...,10,0,0,0,76.0,NaN,NaN,NaN
2,Hana Pratama,hana.pratama3@example.com,Belajar Fundamental Aplikasi Android,107,1,0,0,1099.0,NaN,163.0,NaN
3,Dina Utama,dina.utama4@example.com,Belajar Fundamental Aplikasi Android,107,0,0,0,1099.0,NaN,163.0,NaN
4,Rafi Santoso,rafi.santoso5@example.com,Belajar Fundamental Aplikasi Android,107,55,0,0,1099.0,NaN,163.0,NaN

In [22]:
for i in range(5):
    df = eval(f"df_{i+1}")     # ambil dataframe
    
    # 1. Print total missing value
    print(df.isnull().sum().sum())

0
0
0
1
518

In [23]:
list_of_dict = {}

for i in range(5):
    df = eval(f"df_{i+1}")
    list_of_dict[i+1] = df.to_dict("records")

In [24]:
db = client["learning_buddy_db"]

In [25]:
collection_names = [
    "Learning_Path_Answer",
    "Current_Interest_Questions",
    "Current_Tech_Questions",
    "Skill_Keywords",
    "Student_Progress"
]

collections = {}   # tempat menyimpan semua collection

for i, name in enumerate(collection_names, start=1):
    collections[i] = db.create_collection(name)

In [26]:
for i in range(1, 6):
    collections[i].insert_many(list_of_dict[i])

In [27]:
for i in range(1, 6):
    print(collections[i].count_documents({}))

67
20
326
5553
271