In [1]:
import pandas
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

In [ ]:
uri = "mongodb+srv://Sujatmiko:Sujatmiko123@learning-buddy.jlyprnn.mongodb.net/?appName=Learning-Buddy"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [3]:
df_1= pandas.read_excel('CourseMapping.xlsx', sheet_name='LP + Course')
df_2= pandas.read_excel('CourseMapping.xlsx', sheet_name='Learning Path')
df_3= pandas.read_excel('CourseMapping.xlsx', sheet_name='Course')
df_4= pandas.read_excel('CourseMapping.xlsx', sheet_name='Tutorials')
df_5= pandas.read_excel('CourseMapping.xlsx', sheet_name='Course Level')

In [4]:
df_4 = df_4.drop(columns=["Unnamed: 3", "Unnamed: 4"])

In [5]:
display (df_1.head())
display (df_2.head())
display (df_3.head())
display (df_4.head())
display (df_5.head())

,learning_path_name,course_name,course_level_str,tutorial_title
0,AI Engineer,Belajar Dasar AI,Dasar,Taksonomi AI
1,AI Engineer,Belajar Dasar AI,Dasar,[Story] Machine Learning: Harapan menjadi keny...
2,AI Engineer,Belajar Dasar AI,Dasar,Rangkuman Kelas
3,AI Engineer,Belajar Dasar AI,Dasar,Tipe-Tipe Machine Learning
4,AI Engineer,Belajar Dasar AI,Dasar,Forum Diskusi

   learning_path_id             learning_path_name
0                 1                    AI Engineer
1                 2              Android Developer
2                 3  Back-End Developer JavaScript
3                 4      Back-End Developer Python
4                 5                 Data Scientist

,course_id,learning_path_id,course_name,course_level_str,hours_to_study
0,1,1,Belajar Dasar AI,1,10
1,2,1,Belajar Fundamental Deep Learning,3,110
2,3,1,Belajar Machine Learning untuk Pemula,2,90
3,4,1,Machine Learning Terapan,4,80
4,5,1,Membangun Proyek Deep Learning Tingkat Mahir,4,90

   tutorial_id  course_id                                     tutorial_title
0            1          1                                       Taksonomi AI
1            2          1  [Story] Machine Learning: Harapan menjadi keny...
2            3          1                                    Rangkuman Kelas
3            4          1                         Tipe-Tipe Machine Learning
4            5          1                                      Forum Diskusi

   id course_level
0   1        Dasar
1   2       Pemula
2   3     Menengah
3   4        Mahir
4   5  Profesional

In [6]:
for i in range(5):
    df = eval(f"df_{i+1}")     # ambil dataframe
    
    # 1. Print total missing value
    print(df.isnull().sum().sum())

0
0
0
0
0

In [7]:
list_of_dict = {}

for i in range(5):
    df = eval(f"df_{i+1}")
    list_of_dict[i+1] = df.to_dict("records")

In [8]:
db = client["learning_buddy_db"]

In [9]:
collection_names = [
    "LP+Course",
    "Learning_Path",
    "Course",
    "Tutorials",
    "Course_Level"
]

collections = {}   # tempat menyimpan semua collection

for i, name in enumerate(collection_names, start=1):
    collections[i] = db.create_collection(name)

In [10]:
for i in range(1, 6):
    collections[i].insert_many(list_of_dict[i])

In [ ]:
for i in range(1, 6):
    print(collections[i].count_documents({}))

7916
13
75
7771
5